[build]
command = "npm install"
publish = "."

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/github/folder"
to = "/.netlify/functions/github-folder"
status = 200

[[redirects]]
from = "/github/file"
to = "/.netlify/functions/github-single"
status = 200