openapi: 3.1.0
info:
  title: GitHub Folder Reader API
  version: 1.0.0
paths:
  /github/folder:
    get:
      operationId: getFolderFiles
      summary: Get all file contents from a GitHub folder
      parameters:
        - name: repo
          in: query
          required: true
          schema:
            type: string
          example: "t0021583/TRPG-Database"
        - name: path
          in: query
          required: true
          schema:
            type: string
          example: "bedroom"
        - name: branch
          in: query
          required: false
          schema:
            type: string
          example: "main"
      responses:
        '200':
          description: Folder files and contents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    filename:
                      type: string
                    content:
                      type: string
servers:
  - url: https://trpg0703.netlify.app
